# Railway configuration for ShedSuite Inventory → Supabase service

[build]
builder = "NIXPACKS"

[deploy]
startCommand = "npm start"
healthcheckPath = "/health"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[cron]
  [cron.inventory_sync]
  schedule = "*/15 * * * *" # every 15 minutes
  command = "npm run sync"


